{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "A new map with cluster means (per 100K) has been generated: us_clusters_map.html\n"
     ]
    }
   ],
   "source": [
    "# Performs K-Means clustering on the USArrests dataset, calculates crime rate means \n",
    "# per cluster, and visualizes the results on a color-coded interactive map using Folium.\n",
    "\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import folium\n",
    "import json\n",
    "import random\n",
    "import requests\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from collections import Counter, defaultdict\n",
    "\n",
    "\n",
    "US_Arrests_data = pd.read_csv(\"USArrests.csv\") # loads dataset\n",
    "US_states = US_Arrests_data['State'] # extracts the state names\n",
    "\n",
    "# Extract numerical data before scaling to compute actual means later\n",
    "Original_State_Data = US_Arrests_data.iloc[:, 1:5].values  \n",
    "\n",
    "# scales the data for clustering (scale each attribute to have mean 0 and std dev 1 )\n",
    "State_Data = Original_State_Data.copy()\n",
    "scaler = StandardScaler() \n",
    "State_Data = scaler.fit_transform(State_Data) #State_Data is now numpy array with standardized values \n",
    "\n",
    "\n",
    "# K-means clustering functions\n",
    "\n",
    "# computes the squared euclidean distance between vectors x and y\n",
    "def distance(x, y):\n",
    "    return np.sum((x - y) ** 2)\n",
    "\n",
    "# computes the centroid of a cluster (average position of all points in cluster)\n",
    "# X is a matrix that contains the cluster,\n",
    "# with rows as observations and (numeric) columns as attributes\n",
    "def centroid(X): \n",
    "    return np.mean(X, axis=0)\n",
    "\n",
    "# a single iteration of kmeans\n",
    "# X is a matrix of observations with m rows and n columns\n",
    "# k is the number of clusters\n",
    "def kmeans1(X, k):\n",
    "    m, n = X.shape\n",
    "    if k > m:\n",
    "        # logically, num clusters cannot excede observations\n",
    "        raise ValueError(f\"number of clusters {k} > number of observations {m}\")  \n",
    "\n",
    "    # random initial assignment of each observation to a cluster \n",
    "    clusters0 = np.random.randint(0, k, m)  \n",
    "    # holds the actual cluster assignments \n",
    "    clusters = np.zeros(m)\n",
    "\n",
    "    while True:\n",
    "\n",
    "        # initialzes array of centroids\n",
    "        c = np.zeros((k, n))  \n",
    "\n",
    "        # computes the cluster centroids\n",
    "        for i in range(k):\n",
    "            # cenroid of cluster i placed in c\n",
    "            c[i, :] = centroid(X[clusters0 == i])\n",
    "\n",
    "        # assign each observation to the nearest centroid\n",
    "        for i in range(m):  # loop over each data point\n",
    "            clusters[i] = 0  # initially assign to cluster 0\n",
    "            best = distance(X[i, :], c[0, :])  # compute distance to first centroid\n",
    "            \n",
    "            # compare with other centroids\n",
    "            for j in range(1, k):\n",
    "                candidate = distance(X[i, :], c[j, :])  # compute distance\n",
    "\n",
    "                if candidate < best:  # if closer, update assignment\n",
    "                    best = candidate\n",
    "                    clusters[i] = j\n",
    "\n",
    "        # when the clusters stop changing\n",
    "        if np.array_equal(clusters, clusters0): \n",
    "            break  \n",
    "\n",
    "        clusters0 = clusters.copy()\n",
    "\n",
    "    clusters_assigned = len(Counter(clusters))\n",
    "    if clusters_assigned != k:\n",
    "        raise ValueError(f\"clustering solution contains {clusters_assigned} < {k} clusters.\")\n",
    "    return clusters\n",
    "\n",
    "# computes the value of the kmeans objective\n",
    "# function, the sum of the within-cluster distances.\n",
    "# X is the matrix of observations.\n",
    "# k is the number of clusters.\n",
    "# cl is the clustering solution.\n",
    "def objective(X, k, cl):\n",
    "    sum_dist = 0 #tracks sum of the distances to centroids in each cluster\n",
    "    for i in range(k):  \n",
    "        cluster_i_obs = X[cl == i]  # find all the points in X that are in cluster i\n",
    "        if len(cluster_i_obs) > 0: # finds centroid of the cluster only if there are points in it\n",
    "            centroid_clust_i = centroid(cluster_i_obs)\n",
    "            sum_dist += sum(distance(observation, centroid_clust_i) for observation in cluster_i_obs) #adds this distance to the sum of distances for minimizing later\n",
    "    return sum_dist\n",
    "\n",
    "\n",
    "# driver function for kmeans.\n",
    "# X is the (scaled) matrix of observations.\n",
    "# k is the number of clusters.\n",
    "# niter is the number of times to run the k-means algorithm.\n",
    "# the best of the niter candidate solutions is returned.\n",
    "def kmeans(X, k, niter=50):\n",
    "    smallest_dist = float(\"inf\")\n",
    "    final_cl = np.zeros(X.shape[0])\n",
    "    for i in range(niter):\n",
    "        solution = kmeans1(X, k)\n",
    "        sum_distances = objective(X, k, solution)\n",
    "        if sum_distances < smallest_dist:\n",
    "            smallest_dist = sum_distances\n",
    "            final_cl = solution\n",
    "    return final_cl\n",
    "\n",
    "# Run k-means\n",
    "num_clusters = 4\n",
    "cl = kmeans(State_Data, num_clusters)\n",
    "\n",
    "# Assign states to clusters\n",
    "states_in_cluster = defaultdict(list)\n",
    "for i, state in enumerate(US_states):\n",
    "    states_in_cluster[int(cl[i])].append(state)\n",
    "\n",
    "# Compute actual means per cluster\n",
    "cluster_actual_means = {}\n",
    "for cluster, states in states_in_cluster.items():\n",
    "    indices = [US_states[US_states == state].index[0] for state in states]  \n",
    "    cluster_actual_means[cluster] = np.mean(Original_State_Data[indices], axis=0)  \n",
    "\n",
    "# U.S. state boundaries from GeoJSON\n",
    "geojson_url = \"https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json\"\n",
    "geojson_data = requests.get(geojson_url).json()\n",
    "\n",
    "# color generated for each cluster and each state mapped to its cluster color\n",
    "cluster_colors = {cluster: \"#{:06x}\".format(random.randint(0, 0xFFFFFF)) for cluster in states_in_cluster}\n",
    "state_cluster_map = {state: cluster_colors[cluster] for cluster, states in states_in_cluster.items() for state in states}\n",
    "\n",
    "us_map = folium.Map(location=[37.8, -96], zoom_start=4)\n",
    "\n",
    "# styles each state based on its cluster\n",
    "def style_function(feature):\n",
    "    state_name = feature['properties']['name']\n",
    "    color = state_cluster_map.get(state_name, \"#d3d3d3\")  # default grey if state not found\n",
    "    return {'fillColor': color, 'color': 'black', 'weight': 1, 'fillOpacity': 0.7}\n",
    "\n",
    "# adds states layer with colors\n",
    "folium.GeoJson(\n",
    "    geojson_data,\n",
    "    name=\"Clusters\",\n",
    "    style_function=style_function\n",
    ").add_to(us_map)\n",
    "\n",
    "# generates cluster summary HTML to be added to map\n",
    "cluster_summary_html = \"<h4>Cluster Summary (Crime Rates per 100K)</h4><ul>\"\n",
    "for cluster, states in states_in_cluster.items():\n",
    "    means = cluster_actual_means[cluster]\n",
    "    cluster_summary_html += (f\"<li><b>Cluster {cluster + 1}</b>: \"\n",
    "                             f\"{len(states)} states<br>\"\n",
    "                             f\"Murder: {means[0]:.2f} per 100K<br>\"\n",
    "                             f\"Assault: {means[1]:.2f} per 100K<br>\"\n",
    "                             f\"UrbanPop: {means[2]:.2f}%<br>\"\n",
    "                             f\"Rape: {means[3]:.2f} per 100K<br>\"\n",
    "                             f\"States: {', '.join(states)}</li><br>\")\n",
    "cluster_summary_html += \"</ul>\"\n",
    "\n",
    "# adds floating text box with actual cluster means\n",
    "html_popup = folium.Html(cluster_summary_html, script=True)\n",
    "popup = folium.Popup(html_popup, max_width=600)\n",
    "folium.Marker([49, -125], icon=folium.Icon(color=\"blue\", icon=\"info-sign\"), popup=popup).add_to(us_map)\n",
    "\n",
    "# layer control\n",
    "folium.LayerControl().add_to(us_map)\n",
    "\n",
    "# saves and displays the map\n",
    "us_map.save(\"us_clusters_map.html\")\n",
    "print(\"A new map with cluster means (per 100K) has been generated: us_clusters_map.html\")\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
